"""
⚙️ 配置常量模块

存放所有配置相关的常量
"""

# API 配置
BASE_URL = "https://r0semi.xtower.site/api/v1/open"
DEFAULT_API_TOKEN = ""

# HTTP 配置
HTTP_TIMEOUT = 30
HTTP_CONNECT_TIMEOUT = 10
HTTP_SOCK_READ_TIMEOUT = 20
HTTP_POOL_SIZE = 50
HTTP_POOL_PER_HOST = 20

# 缓存配置
CACHE_TTL = 300  # 5 分钟
CACHE_CLEAN_INTERVAL = 600  # 10 分钟

# 图片配置
DEFAULT_IMAGE_QUALITY = 95
DEFAULT_IMAGE_FORMAT = "PNG"
PNG_COMPRESS_LEVEL = 1  # 1-9, 1 为最快

# 路径配置
DEFAULT_ILLUSTRATION_PATH = "./ILLUSTRATION"
DEFAULT_AVATAR_PATH = "./AVATAR"
DEFAULT_TAPTAP_VERSION = "cn"

# 搜索配置
DEFAULT_SEARCH_LIMIT = 5
DEFAULT_HISTORY_LIMIT = 10

# 渲染配置
RENDERER_WIDTH = 1200
RENDERER_HEADER_HEIGHT = 180
RENDERER_CARD_WIDTH = 360
RENDERER_CARD_HEIGHT = 100
RENDERER_CARD_MARGIN = 15

# 字体配置
FONT_CACHE_SIZE = 50

# 登录配置
QR_LOGIN_TIMEOUT = 120  # 二维码有效期 2 分钟
QR_POLL_INTERVAL = 2  # 轮询间隔 2 秒

# 更新配置
ILLUSTRATION_UPDATE_INTERVAL = 7  # 7 天检查一次更新
ILLUSTRATION_UPDATE_TIMEOUT = 300  # 5 分钟下载超时
